'DESK_SUBDOMAIN': 'jackxxu'
'CONSUMER_KEY': 'McWpDdWUtnYN6hjiRWvb'
'CONSUMER_SECRET': 'vG0QSF60hZQb129mKMoUSPgm8wKi1lvAbMEiCJac'
'OAUTH_TOKEN': 'SpVc2bt8OyZSRBUIqf1I'
'OAUTH_TOKEN_SECRET': 'mrPiiMlttJJjfNbHzKOWb3eTRIsncoIiHjxESuUQ'
